export { default as Navbar } from './Navbar'
export { default as HomePage } from './HomePage'
export { default as Exchanges } from './Exchanges'
export { default as Cryptocurrentcies } from './Cryptocurrentcies'
export { default as CryptoDetail } from './CryptoDetail'
export { default as News } from './News'
